---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: _recipes
  label: Recipes
  create: documents
  match: "**/*"
  templates:
  - recipe-single
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - recipes-list
  - default
- type: document
  path: _data/taxonomies.yml
  label: Taxonomies
upload_dir: bisou
public_path: https://res.cloudinary.com/userID/image/upload #replace "userID" by your cloudinary userID
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=master
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
