remote_theme: pfdt/bisou-jekyll-theme@master

collections:
  recipes:
    output: true
    permalink: "/:path/"
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe-single
      date: 1970-01-01 00:00:00
  - scope:
      path: "admin/*"
    values:
      sitemap: false

sass:
  style: compressed
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: all

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

exclude:
- ".gitignore"
- ".gitattributes"
- ".jekyll-cache"
- "sample_content/"
- CNAME
- README.md