title: bisou #site title
description: a cocktail recipes jekyll theme #site description
urlbase:  #site urlbase
url:  #site url
permalink: "/:path/"

img-dir--card: https://res.cloudinary.com/userID/image/upload/c_fill,g_auto:no_faces,h_465,q_80,w_600/f_auto #img baseurl for card images (for cloudinary replace "userID" by yours
img-dir--sharing: https://res.cloudinary.com/userID/image/upload/c_fill,g_auto:no_faces,h_630,w_1200/f_auto #img baseurl for sharing images (for cloudinary replace "userID" by yours
googlanalytics_ID: "" #add your UA ID if needed
firebase_apiKey: "" #apiKey of your firebase realtime database (for collection and ratings functions)
firebase_projectId: "" #projectId of your firebase realtime database (for collection and ratings functions)
firebase_databaseName: "" #databaseName of your firebase realtime database (for collection and ratings functions)

collections:
  recipes:
    output: true
    permalink: "/:path/"
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe-single
      date: 1970-01-01 00:00:00

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: all

remote_theme: pfdt/bisou-jekyll-theme

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

exclude:
- ".gitignore"
- ".gitattributes"
- ".jekyll-cache"
- "sample_content/"
- CNAME
- README.md