title: bisou #site title
description: a cocktail recipes jekyll theme #site description
urlbase:  #site urlbase
url:  #site url
permalink: "/:path/"

img-transform--card: ?nf_resize=smartcrop&w=600&h=465 #Netlify Large Media img transform parameters for card images
img-transform--sharing: ?nf_resize=smartcrop&w=1200&h=630 #Netlify Large Media img transform parameters for sharing images
googlanalytics_ID: "" #add your UA ID if needed
firebase_apiKey: "" #apiKey of your firebase realtime database (for collection and ratings functions)
firebase_projectId: "" #projectId of your firebase realtime database (for collection and ratings functions)
firebase_databaseName: "" #databaseName of your firebase realtime database (for collection and ratings functions)

collections:
  recipes:
    output: true
    permalink: "/:path/"
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe-single
      date: 1970-01-01 00:00:00

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: all

remote_theme: pfdt/bisou-jekyll-theme

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

exclude:
- ".gitignore"
- ".gitattributes"
- ".jekyll-cache"
- "sample_content/"
- CNAME
- README.md